import { Rubik } from "@next/font/google";
import cn from "classnames";
import Head from "next/head";
import { Footer } from "./footer";
import { Header } from "./header";

const rubik = Rubik({ subsets: ["latin"], display: "swap" });

interface LayoutProps {
  children: React.ReactNode;
}

export function Layout({ children }: LayoutProps) {
  return (
    <div
      className={cn(
        "mx-auto flex min-h-screen max-w-screen-sm flex-col px-4",
        rubik.className
      )}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="flex-1">{children}</main>
      <Footer />
    </div>
  );
}
